--- #YAML:1.0
name: Posy-Plugin-LinkExtra
version: 0.41
author:
  - Kathryn Andersen
abstract: Posy plugin to add extras to local links.
license: perl
requires:
  File::Spec: 3.01
  Posy: 0.9
  Posy::Plugin::FileStats: 0.5
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::LinkExtra:
    file: lib/Posy/Plugin/LinkExtra.pm
    version: 0.41
generated_by: Module::Build version 0.2607
